### ISSUE TITLE
[remove] dev_deploy.yml 파일에서 사용되지 않는 부분 삭제

### ISSUE THREAD

**Issue by yel-m** [SSU-Capstone-Aurora/CareVision-Backend#36]
## 📝 개요
> 현재 Code Deploy 배포의 Application 훅에서 오류가 나는 이유를 찾고 있습니다. 
  <img width="1115" alt="image" src="https://github.com/user-attachments/assets/d89d3292-5457-4fd7-b5bc-63e4a04f10f3">

- (이게 원인이 아닐 확률이 크지만)` dev_deploy.yml`에 있는 다음 코드는 `application.yml`에 다음과 같은 설정이 있어야 의미가 있으므로 지금은 삭제합니다.
  - 리소스(이미지, 비디오 등)를 위한 S3 버킷을 생성할 경우 추후 추가하겠습니다!
  ```yml
  cloud.aws.credentials.access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  cloud.aws.credentials.secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ```
  ```yml
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY} # cloud.aws.credentials.access-key에 해당
        secret-key: ${SECRET_KEY}  # cloud.aws.credentials.secret-key에 해당
      region:
        static: 버킷리전
      s3:
        bucket: 버킷이름
      stack:
        auto: false
  ```
- 이 부분 또한 ElasticBeanstalk과 관련된 부분이므로 삭제합니다.
  ```yml
  - name: Generate deployment package
    run: |
      mkdir -p deploy
      cp build/libs/*SNAPSHOT.jar deploy/application.jar
      cd deploy && zip -r deploy.zip .
  ```

## ✔️ 작업 상세 내용
dev_deploy.yml 파일에서
- [x] 리소스를 위한 S3 버킷 환경 설정 삭제
- [x] Generate deployment package 스텝 삭제

## 🔗 참고자료(선택)
- 참고자료 등 기타 내용 작성
